### ISSUE TITLE
Null reference on Day.Post

### ISSUE THREAD

**Issue by MAX0690** [DieNullpointer/triptales#112]
When creating a Day the Post attribute is null

If you try to delete a day and want to compare the author of the post and the current user you get a null reference on day.post

A day should always have a day and this attribute shouln't be able to be null.

![Screenshot 2023-12-07 175242](https://github.com/DieNullpointer/triptales/assets/120011258/85253bbe-3ac4-4926-99c3-05644f7d8819)

**Comment by BastiMagOrangen** [comment]
Schau ich mir an
