### ISSUE TITLE
Fix Duplicate Notifications

### ISSUE THREAD

**Issue by phil-not-funny** [DieNullpointer/triptales#161]
**Describe the bug**
This bug occurs when a user reproduces the same notification. It should not be shown twice

**To Reproduce**
1. Follow a user/like a post
2. Unfollow/unlike
3. Follow user/like post again
4. The recipient sees the notification twice 

**Expected behavior**
After unfollowing/unliking, a notification should be deleted

**Comment by BastiMagOrangen** [comment]
@phil-not-funny 

This bug happens, beacause, if the user is unfollowing the old notification is still saved.

Will be fixed soon
