### ISSUE TITLE
feature: frontend - footer

### ISSUE THREAD

**Issue by phil-not-funny** [DieNullpointer/triptales#74]
# Beschreibung bitte Lesen

Wireframe: 
![image](https://github.com/DieNullpointer/triptales/assets/77935424/e2a5b7da-6860-44fe-bfa5-344b1cf41f7c)
[Link zum Wireframe](https://wireframe.cc/b5oieT)

- Das Bild in der Mitte sollte unser Logo sein.
- Das Copyright Symbol kannst du mit &copy machen
- Um die 3 Spalten hin zu bekommen kann unser **self-made Grid component** oder die **Tailwind Klassen** flex, justify-around, items-center helfen
- Footer soll erst sichtbar sein wenn man nach unten scrollt

**Comment by BastiMagOrangen** [comment]
ok
